# Generated by Django 4.2.7 on 2023-11-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_todo_color_todo_genero_todo_tipe_alter_todo_breed"),
    ]

    operations = [
        migrations.CreateModel(
            name="info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField(verbose_name="Data de Retirada")),
                ("finished_at", models.DateField(null=True)),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
        migrations.CreateModel(
            name="pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Nome do Pet")),
                (
                    "breed",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Raça do Pet"
                    ),
                ),
                (
                    "tipe",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Tipo de Pet"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Cor do Pet"
                    ),
                ),
                (
                    "genero",
                    models.CharField(max_length=100, null=True, verbose_name="Genero"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
        migrations.AddField(
            model_name="info",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todos.pet"
            ),
        ),
    ]
