# Generated by Django 4.2.7 on 2023-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0005_info_pet_delete_todo_info_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="pet",
        ),
        migrations.AddField(
            model_name="info",
            name="breed",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Raça do Pet"
            ),
        ),
        migrations.AddField(
            model_name="info",
            name="color",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Cor do Pet"
            ),
        ),
        migrations.AddField(
            model_name="info",
            name="genero",
            field=models.CharField(max_length=100, null=True, verbose_name="Genero"),
        ),
        migrations.AddField(
            model_name="info",
            name="tipe",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tipo de Pet"
            ),
        ),
        migrations.AddField(
            model_name="info",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Nome do Pet"
            ),
        ),
        migrations.DeleteModel(
            name="pet",
        ),
    ]
