# Generated by Django 4.2.7 on 2023-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0010_alter_info_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="genero",
            field=models.CharField(
                choices=[("macho", "Macho"), ("femea", "Fêmea")],
                max_length=10,
                null=True,
                verbose_name="Gênero",
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="tipe",
            field=models.CharField(
                choices=[
                    ("cachorro", "Cachorro"),
                    ("gato", "Gato"),
                    ("coelho", "Coelho"),
                    ("hamster", "Hamster"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Pet",
            ),
        ),
    ]
