# Generated by Django 4.2.7 on 2023-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0011_alter_info_genero_alter_info_tipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="genero",
            field=models.CharField(
                choices=[("macho", "Macho"), ("femea", "Fêmea")],
                max_length=40,
                null=True,
                verbose_name="Gênero",
            ),
        ),
    ]
