# Generated by Django 4.2.7 on 2023-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0012_alter_info_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="genero",
            field=models.CharField(
                choices=[("macho", "Macho"), ("femea", "Fêmea")],
                max_length=20,
                null=True,
                verbose_name="Gênero",
            ),
        ),
    ]
