# Generated by Django 4.2.7 on 2023-11-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0013_alter_info_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Nome do Pet")),
                (
                    "breed",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Raça do Pet"
                    ),
                ),
                (
                    "tipe",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Tipo de Pet"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Cor do Pet"
                    ),
                ),
                (
                    "genero",
                    models.CharField(max_length=100, null=True, verbose_name="Genero"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField(verbose_name="Data de Retirada")),
                ("finished_at", models.DateField(null=True)),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
        migrations.AlterField(
            model_name="info",
            name="genero",
            field=models.CharField(max_length=100, null=True, verbose_name="Genero"),
        ),
        migrations.AlterField(
            model_name="info",
            name="tipe",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tipo de Pet"
            ),
        ),
    ]
